const User = require('../models/User');
const Property = require('../models/Property');
const BuyerPreferences = require('../models/BuyerPreferences');
const SellerInsights = require('../models/SellerInsights');

const sampleProperties = [
  // ── MUMBAI REGION ──────────────────────────────────────────────────────────
  {
    title: 'Lodha World Towers',
    description: 'Iconic luxury 3BHK high-rise residence overlooking the Arabian Sea and South Mumbai skyline. Premium Italian marble, private elevator access, and multi-tier security.',
    propertyType: 'Apartment',
    listingType: 'Sale',
    price: 45000000,
    pricePerSqFt: 27272,
    location: {
      type: 'Point',
      coordinates: [72.828, 18.995],
      address: 'Lodha World Towers, Lower Parel',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400013',
    },
    specifications: {
      bedrooms: 3, bathrooms: 3, balconies: 2,
      carpetArea: 1650, builtUpArea: 1950,
      floor: 42, totalFloors: 75,
      parkingSpots: 2, facing: 'East',
      furnishingStatus: 'Fully-Furnished', age: 1,
    },
    amenities: ['Lift', 'Gym', 'Swimming Pool', 'Parking', 'Security', 'Power Backup', 'Garden', 'Clubhouse', 'CCTV', 'Intercom', 'Solar Panels', 'Tennis Court'],
    images: ['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1000&q=80', 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1000&q=80'],
    status: 'available',
    sourcePortal: '99acres.com',
    sourceUrl: 'https://www.99acres.com/lodha-world-towers-lower-parel-mumbai-npid-101',
    verifiedLive: true,
    lastSyncedAt: new Date(),
    aiScore: { overall: 94, locationScore: 97, connectivityScore: 96, amenitiesScore: 95, roiPotential: 92, lastScoredAt: new Date() },
    environmentScore: { overall: 85, aqi: 52, aqiLabel: 'Good', greenCover: 72, noiseLevel: 'Moderate' },
    views: 890, saves: 142, inquiries: 38,
  },
  {
    title: 'Oberoi Sky City',
    description: 'Direct access to Western Express Highway Metro line with lush green views of Sanjay Gandhi National Park. High ROI rental demand from corporate hubs.',
    propertyType: 'Apartment',
    listingType: 'Sale',
    price: 26500000,
    pricePerSqFt: 24423,
    location: {
      type: 'Point',
      coordinates: [72.862, 19.228],
      address: 'Western Express Highway, Borivali East',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400066',
    },
    specifications: {
      bedrooms: 3, bathrooms: 3, balconies: 2,
      carpetArea: 1085, builtUpArea: 1350,
      floor: 18, totalFloors: 40,
      parkingSpots: 2, facing: 'North-East',
      furnishingStatus: 'Semi-Furnished', age: 2,
    },
    amenities: ['Lift', 'Gym', 'Swimming Pool', 'Parking', 'Security', 'Power Backup', 'Garden', 'Clubhouse', 'CCTV', 'Children Play Area', 'Jogging Track'],
    images: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80'],
    status: 'available',
    sourcePortal: 'Housing.com',
    sourceUrl: 'https://housing.com/in/buy/resale/page/1029381-oberoi-sky-city-borivali-east',
    verifiedLive: true,
    lastSyncedAt: new Date(),
    aiScore: { overall: 91, locationScore: 92, connectivityScore: 95, amenitiesScore: 90, roiPotential: 89, lastScoredAt: new Date() },
    environmentScore: { overall: 92, aqi: 42, aqiLabel: 'Good', greenCover: 88, noiseLevel: 'Low' },
    views: 654, saves: 89, inquiries: 24,
  },
  {
    title: 'Rustomjee Elements Juhu',
    description: 'Ultra-luxury celebrity enclave residence in Juhu. High ceilings, sunset view balconies, and 3-tier security.',
    propertyType: 'Villa',
    listingType: 'Sale',
    price: 78000000,
    pricePerSqFt: 31836,
    location: {
      type: 'Point',
      coordinates: [72.826, 19.107],
      address: 'Juhu Tara Road, Juhu',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400049',
    },
    specifications: {
      bedrooms: 4, bathrooms: 4, balconies: 3,
      carpetArea: 2450, builtUpArea: 2900,
      floor: 8, totalFloors: 14,
      parkingSpots: 3, facing: 'West',
      furnishingStatus: 'Fully-Furnished', age: 1,
    },
    amenities: ['Lift', 'Gym', 'Swimming Pool', 'Parking', 'Security', 'Power Backup', 'Garden', 'Clubhouse', 'CCTV', 'Intercom', 'Maintenance Staff'],
    images: ['https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=80'],
    status: 'available',
    sourcePortal: 'MagicBricks',
    sourceUrl: 'https://www.magicbricks.com/rustomjee-elements-juhu-mumbai-pdpid-4d4231',
    verifiedLive: true,
    lastSyncedAt: new Date(),
    aiScore: { overall: 96, locationScore: 99, connectivityScore: 94, amenitiesScore: 98, roiPotential: 94, lastScoredAt: new Date() },
    environmentScore: { overall: 90, aqi: 48, aqiLabel: 'Good', greenCover: 80, noiseLevel: 'Low' },
    views: 1240, saves: 210, inquiries: 56,
  },

  // ── THANE REGION ───────────────────────────────────────────────────────────
  {
    title: 'Hiranandani Estate Rodas Enclave',
    description: 'Neoclassical European township living in Thane West with clean Yeoor Hills air quality and high retail convenience.',
    propertyType: 'Apartment',
    listingType: 'Sale',
    price: 18500000,
    pricePerSqFt: 14919,
    location: {
      type: 'Point',
      coordinates: [72.978, 19.262],
      address: 'Rodas Enclave, Hiranandani Estate, Ghodbunder Road',
      city: 'Thane',
      state: 'Maharashtra',
      pincode: '400607',
    },
    specifications: {
      bedrooms: 3, bathrooms: 3, balconies: 2,
      carpetArea: 1240, builtUpArea: 1500,
      floor: 14, totalFloors: 28,
      parkingSpots: 2, facing: 'North',
      furnishingStatus: 'Semi-Furnished', age: 3,
    },
    amenities: ['Lift', 'Gym', 'Swimming Pool', 'Parking', 'Security', 'Power Backup', 'Garden', 'Clubhouse', 'CCTV', 'Rainwater Harvesting', 'Children Play Area'],
    images: ['https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&w=1000&q=80'],
    status: 'available',
    sourcePortal: 'Housing.com',
    sourceUrl: 'https://housing.com/in/buy/resale/page/88192-rodas-enclave-thane',
    verifiedLive: true,
    lastSyncedAt: new Date(),
    aiScore: { overall: 92, locationScore: 91, connectivityScore: 90, amenitiesScore: 94, roiPotential: 95, lastScoredAt: new Date() },
    environmentScore: { overall: 95, aqi: 35, aqiLabel: 'Clean Air', greenCover: 92, noiseLevel: 'Low' },
    views: 489, saves: 76, inquiries: 19,
  },
  {
    title: 'Raymond Realty Ten X Habitat',
    description: 'Smart 2BHK modern living at Majiwada junction with fast access to Eastern Express Highway and Viviana Mall.',
    propertyType: 'Apartment',
    listingType: 'Sale',
    price: 13500000,
    pricePerSqFt: 20149,
    location: {
      type: 'Point',
      coordinates: [72.964, 19.215],
      address: 'Pokhran Road 2, Majiwada',
      city: 'Thane',
      state: 'Maharashtra',
      pincode: '400601',
    },
    specifications: {
      bedrooms: 2, bathrooms: 2, balconies: 1,
      carpetArea: 670, builtUpArea: 850,
      floor: 10, totalFloors: 35,
      parkingSpots: 1, facing: 'East',
      furnishingStatus: 'Unfurnished', age: 1,
    },
    amenities: ['Lift', 'Gym', 'Swimming Pool', 'Parking', 'Security', 'Power Backup', 'Garden', 'CCTV', 'Jogging Track'],
    images: ['https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1000&q=80'],
    status: 'available',
    sourcePortal: '99acres.com',
    sourceUrl: 'https://www.99acres.com/raymond-ten-x-habitat-thane-npid-9901',
    verifiedLive: true,
    lastSyncedAt: new Date(),
    aiScore: { overall: 89, locationScore: 88, connectivityScore: 92, amenitiesScore: 88, roiPotential: 88, lastScoredAt: new Date() },
    environmentScore: { overall: 91, aqi: 38, aqiLabel: 'Good', greenCover: 85, noiseLevel: 'Low' },
    views: 380, saves: 48, inquiries: 15,
  },

  // ── NAVI MUMBAI REGION ─────────────────────────────────────────────────────
  {
    title: 'Wadhwa Wise City Panvel',
    description: 'Integrated township situated near upcoming Navi Mumbai International Airport and MTHL Sea Link. Exceptional 11.4% 5-year ROI potential.',
    propertyType: 'Apartment',
    listingType: 'Sale',
    price: 7800000,
    pricePerSqFt: 12480,
    location: {
      type: 'Point',
      coordinates: [73.117, 18.989],
      address: 'Old Mumbai-Pune Hwy, Panvel',
      city: 'Navi Mumbai',
      state: 'Maharashtra',
      pincode: '410206',
    },
    specifications: {
      bedrooms: 2, bathrooms: 2, balconies: 1,
      carpetArea: 625, builtUpArea: 780,
      floor: 6, totalFloors: 22,
      parkingSpots: 1, facing: 'East',
      furnishingStatus: 'Semi-Furnished', age: 1,
    },
    amenities: ['Lift', 'Gym', 'Swimming Pool', 'Parking', 'Security', 'Power Backup', 'Garden', 'Clubhouse', 'Solar Panels'],
    images: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80'],
    status: 'available',
    sourcePortal: 'Housing.com',
    sourceUrl: 'https://housing.com/in/buy/resale/page/77210-wadhwa-wise-city-panvel',
    verifiedLive: true,
    lastSyncedAt: new Date(),
    aiScore: { overall: 88, locationScore: 84, connectivityScore: 89, amenitiesScore: 86, roiPotential: 96, lastScoredAt: new Date() },
    environmentScore: { overall: 96, aqi: 28, aqiLabel: 'Clean Air Zone', greenCover: 95, noiseLevel: 'Very Low' },
    views: 512, saves: 94, inquiries: 27,
  },
  {
    title: 'L&T Seawoods Residences',
    description: "India's premier Transit-Oriented Development (TOD) built right on top of Seawoods Grand Central Mall and Seawoods Railway Station.",
    propertyType: 'Apartment',
    listingType: 'Sale',
    price: 21500000,
    pricePerSqFt: 19196,
    location: {
      type: 'Point',
      coordinates: [73.018, 19.021],
      address: 'Seawoods Railway Station Complex, Seawoods',
      city: 'Navi Mumbai',
      state: 'Maharashtra',
      pincode: '400706',
    },
    specifications: {
      bedrooms: 3, bathrooms: 3, balconies: 2,
      carpetArea: 1120, builtUpArea: 1400,
      floor: 12, totalFloors: 26,
      parkingSpots: 2, facing: 'North-West',
      furnishingStatus: 'Fully-Furnished', age: 2,
    },
    amenities: ['Lift', 'Gym', 'Swimming Pool', 'Parking', 'Security', 'Power Backup', 'Garden', 'Clubhouse', 'CCTV', 'Intercom', 'Maintenance Staff'],
    images: ['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1000&q=80'],
    status: 'available',
    sourcePortal: '99acres.com',
    sourceUrl: 'https://www.99acres.com/l-and-t-seawoods-residences-navi-mumbai-npid-4410',
    verifiedLive: true,
    lastSyncedAt: new Date(),
    aiScore: { overall: 95, locationScore: 98, connectivityScore: 99, amenitiesScore: 94, roiPotential: 91, lastScoredAt: new Date() },
    environmentScore: { overall: 90, aqi: 44, aqiLabel: 'Good', greenCover: 78, noiseLevel: 'Low' },
    views: 740, saves: 128, inquiries: 39,
  },
  {
    title: 'Hiranandani Gardens Powai Castle Rock',
    description: 'Boutique luxury 2BHK residence in Powai overlook Powai Lake and lush green hillocks. High NRI rental demand and IT hub proximity.',
    propertyType: 'Apartment',
    listingType: 'Sale',
    price: 31000000,
    pricePerSqFt: 28181,
    location: {
      type: 'Point',
      coordinates: [72.908, 19.117],
      address: 'Central Avenue, Hiranandani Gardens, Powai',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400076',
    },
    specifications: {
      bedrooms: 2, bathrooms: 2, balconies: 1,
      carpetArea: 820, builtUpArea: 1100,
      floor: 16, totalFloors: 32,
      parkingSpots: 1, facing: 'East',
      furnishingStatus: 'Fully-Furnished', age: 1,
    },
    amenities: ['Lift', 'Gym', 'Swimming Pool', 'Parking', 'Security', 'Power Backup', 'Garden', 'Clubhouse', 'CCTV'],
    images: ['https://images.unsplash.com/photo-1567496898669-ee935f5f647a?auto=format&fit=crop&w=1000&q=80'],
    status: 'available',
    sourcePortal: 'MagicBricks',
    sourceUrl: 'https://www.magicbricks.com/hiranandani-powai-mumbai-pdpid-1120',
    verifiedLive: true,
    lastSyncedAt: new Date(),
    aiScore: { overall: 93, locationScore: 96, connectivityScore: 94, amenitiesScore: 95, roiPotential: 92, lastScoredAt: new Date() },
    environmentScore: { overall: 94, aqi: 42, aqiLabel: 'Good', greenCover: 88, noiseLevel: 'Low' },
    views: 890, saves: 160, inquiries: 42,
  },
  {
    title: 'K Raheja Vivarea Mahalaxmi',
    description: 'Opulent 3BHK high-rise apartment with unhindered views of the Mahalaxmi Racecourse and Arabian Sea. Private lift lobby and spa.',
    propertyType: 'Apartment',
    listingType: 'Sale',
    price: 85000000,
    pricePerSqFt: 38636,
    location: {
      type: 'Point',
      coordinates: [72.825, 18.983],
      address: 'Sane Guruji Marg, Mahalaxmi',
      city: 'Mumbai',
      state: 'Maharashtra',
      pincode: '400011',
    },
    specifications: {
      bedrooms: 3, bathrooms: 3, balconies: 2,
      carpetArea: 2200, builtUpArea: 2650,
      floor: 28, totalFloors: 45,
      parkingSpots: 3, facing: 'West',
      furnishingStatus: 'Fully-Furnished', age: 2,
    },
    amenities: ['Lift', 'Gym', 'Swimming Pool', 'Parking', 'Security', 'Power Backup', 'Garden', 'Clubhouse', 'Intercom', 'Tennis Court'],
    images: ['https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1000&q=80'],
    status: 'available',
    sourcePortal: '99acres.com',
    sourceUrl: 'https://www.99acres.com/k-raheja-vivarea-mahalaxmi-mumbai-npid-5541',
    verifiedLive: true,
    lastSyncedAt: new Date(),
    aiScore: { overall: 96, locationScore: 98, connectivityScore: 97, amenitiesScore: 96, roiPotential: 93, lastScoredAt: new Date() },
    environmentScore: { overall: 84, aqi: 55, aqiLabel: 'Moderate', greenCover: 70, noiseLevel: 'Moderate' },
    views: 1120, saves: 195, inquiries: 51,
  },
  {
    title: 'Godrej Emerald Ghodbunder',
    description: 'Eco-friendly residence nestled beside Yeoor Hills with over 5 acres of open green spaces and bird-watching decks.',
    propertyType: 'Apartment',
    listingType: 'Sale',
    price: 11500000,
    pricePerSqFt: 14743,
    location: {
      type: 'Point',
      coordinates: [72.969, 19.278],
      address: 'Ghodbunder Road, Bhayandarpada',
      city: 'Thane',
      state: 'Maharashtra',
      pincode: '400615',
    },
    specifications: {
      bedrooms: 2, bathrooms: 2, balconies: 1,
      carpetArea: 780, builtUpArea: 950,
      floor: 12, totalFloors: 29,
      parkingSpots: 1, facing: 'North-East',
      furnishingStatus: 'Unfurnished', age: 1,
    },
    amenities: ['Lift', 'Gym', 'Swimming Pool', 'Parking', 'Security', 'Power Backup', 'Garden', 'Clubhouse', 'Rainwater Harvesting'],
    images: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80'],
    status: 'available',
    sourcePortal: 'Housing.com',
    sourceUrl: 'https://housing.com/in/buy/resale/page/99120-godrej-emerald-thane',
    verifiedLive: true,
    lastSyncedAt: new Date(),
    aiScore: { overall: 90, locationScore: 89, connectivityScore: 88, amenitiesScore: 92, roiPotential: 94, lastScoredAt: new Date() },
    environmentScore: { overall: 97, aqi: 32, aqiLabel: 'Clean Air', greenCover: 94, noiseLevel: 'Low' },
    views: 430, saves: 65, inquiries: 22,
  },
  {
    title: 'Godrej Bayview Vashi',
    description: 'Waterfront luxury 3BHK tower offering panoramic views of Thane Creek and Palm Beach Road. Quick access to MTHL Sea Link.',
    propertyType: 'Apartment',
    listingType: 'Sale',
    price: 28500000,
    pricePerSqFt: 21923,
    location: {
      type: 'Point',
      coordinates: [72.998, 19.077],
      address: 'Sector 9, Vashi',
      city: 'Navi Mumbai',
      state: 'Maharashtra',
      pincode: '400703',
    },
    specifications: {
      bedrooms: 3, bathrooms: 3, balconies: 2,
      carpetArea: 1300, builtUpArea: 1620,
      floor: 18, totalFloors: 24,
      parkingSpots: 2, facing: 'West',
      furnishingStatus: 'Semi-Furnished', age: 1,
    },
    amenities: ['Lift', 'Gym', 'Swimming Pool', 'Parking', 'Security', 'Power Backup', 'Garden', 'Clubhouse', 'CCTV', 'Solar Panels'],
    images: ['https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=80'],
    status: 'available',
    sourcePortal: 'MagicBricks',
    sourceUrl: 'https://www.magicbricks.com/godrej-bayview-vashi-navi-mumbai-pdpid-9921',
    verifiedLive: true,
    lastSyncedAt: new Date(),
    aiScore: { overall: 94, locationScore: 97, connectivityScore: 96, amenitiesScore: 93, roiPotential: 93, lastScoredAt: new Date() },
    environmentScore: { overall: 92, aqi: 38, aqiLabel: 'Good', greenCover: 82, noiseLevel: 'Low' },
    views: 780, saves: 135, inquiries: 40,
  },
  {
    title: 'Paradise Sai World City Kharghar',
    description: 'Cosmopolitan mega-township in Kharghar Sector 36 opposite Central Park and Golf Course. High infrastructure growth zone.',
    propertyType: 'Apartment',
    listingType: 'Sale',
    price: 14500000,
    pricePerSqFt: 15263,
    location: {
      type: 'Point',
      coordinates: [73.067, 19.047],
      address: 'Sector 36, Kharghar',
      city: 'Navi Mumbai',
      state: 'Maharashtra',
      pincode: '410210',
    },
    specifications: {
      bedrooms: 2, bathrooms: 2, balconies: 1,
      carpetArea: 950, builtUpArea: 1180,
      floor: 14, totalFloors: 38,
      parkingSpots: 1, facing: 'North',
      furnishingStatus: 'Semi-Furnished', age: 2,
    },
    amenities: ['Lift', 'Gym', 'Swimming Pool', 'Parking', 'Security', 'Power Backup', 'Garden', 'Clubhouse', 'Jogging Track'],
    images: ['https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=80'],
    status: 'available',
    sourcePortal: 'Housing.com',
    sourceUrl: 'https://housing.com/in/buy/resale/page/66541-sai-world-city-kharghar',
    verifiedLive: true,
    lastSyncedAt: new Date(),
    aiScore: { overall: 91, locationScore: 92, connectivityScore: 90, amenitiesScore: 94, roiPotential: 95, lastScoredAt: new Date() },
    environmentScore: { overall: 96, aqi: 30, aqiLabel: 'Clean Air', greenCover: 94, noiseLevel: 'Low' },
    views: 690, saves: 115, inquiries: 33,
  }
];

const autoSeed = async () => {
  try {
    const propCount = await Property.countDocuments();
    if (propCount >= sampleProperties.length) {
      console.log(`ℹ️ Database already contains ${propCount} verified properties.`);
      return;
    }

    console.log('🌱 Refreshing database with high-fidelity real estate properties across Mumbai, Thane, Navi Mumbai...');
    await Property.deleteMany({});
    await User.deleteMany({ email: { $in: ['seller@smartsite.com', 'buyer@smartsite.com'] } });
    const seller = await User.create({
      name: 'Raj Properties',
      email: 'seller@smartsite.com',
      password: 'password123',
      role: 'seller',
      phone: '+91 98765 43210',
      isVerified: true,
    });

    const buyer = await User.create({
      name: 'Rahul Sharma',
      email: 'buyer@smartsite.com',
      password: 'password123',
      role: 'buyer',
      phone: '+91 91234 56789',
      isVerified: true,
    });

    await BuyerPreferences.create({
      user: buyer._id,
      preferredPropertyTypes: ['Apartment', 'Villa'],
      listingPreference: 'Sale',
      budget: { min: 5000000, max: 50000000 },
      preferredLocations: ['Bangalore', 'Mumbai', 'Whitefield'],
      minBedrooms: 2,
      requiredAmenities: ['Gym', 'Parking'],
      buyerSegment: 'family',
      weights: {
        price: 0.30,
        location: 0.30,
        amenities: 0.20,
        connectivity: 0.10,
        roiPotential: 0.10,
      },
      referencePoint: {
        type: 'Point',
        coordinates: [77.6410, 12.9716],
      },
      isComplete: true,
    });

    const createdProperties = [];
    for (const propData of sampleProperties) {
      const property = await Property.create({
        ...propData,
        seller: seller._id,
      });
      createdProperties.push(property);
    }

    for (const property of createdProperties) {
      const aiScore = property.aiScore || {};
      await SellerInsights.create({
        property: property._id,
        seller: seller._id,
        currentScore: {
          overall: aiScore.overall || 70,
          locationScore: aiScore.locationScore || 70,
          connectivityScore: aiScore.connectivityScore || 70,
          amenitiesScore: aiScore.amenitiesScore || 70,
          roiPotential: aiScore.roiPotential || 70,
        },
        scoreHistory: [
          { score: (aiScore.overall || 70) - 8, recordedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000), reason: 'Initial scoring' },
          { score: (aiScore.overall || 70) - 3, recordedAt: new Date(Date.now() - 15 * 24 * 60 * 60 * 1000), reason: 'Added amenities' },
          { score: aiScore.overall || 70, recordedAt: new Date(), reason: 'Latest analysis' },
        ],
        demandStats: {
          totalViews: property.views,
          uniqueViews: Math.round(property.views * 0.7),
          totalSaves: property.saves,
          totalInquiries: property.inquiries,
          weeklyTrend: [
            { week: '2026-W10', views: Math.round(property.views * 0.1), inquiries: Math.round(property.inquiries * 0.1) },
            { week: '2026-W11', views: Math.round(property.views * 0.12), inquiries: Math.round(property.inquiries * 0.12) },
            { week: '2026-W12', views: Math.round(property.views * 0.15), inquiries: Math.round(property.inquiries * 0.15) },
            { week: '2026-W13', views: Math.round(property.views * 0.18), inquiries: Math.round(property.inquiries * 0.2) },
            { week: '2026-W14', views: Math.round(property.views * 0.2), inquiries: Math.round(property.inquiries * 0.22) },
            { week: '2026-W15', views: Math.round(property.views * 0.25), inquiries: Math.round(property.inquiries * 0.2) },
          ],
        },
        demandLevel: property.inquiries > 20 ? 'very_high' : property.inquiries > 10 ? 'high' : 'moderate',
        buyerSegmentMatch: {
          family: 75,
          investor: 60,
          student: 25,
          bachelor: 35,
          retiree: 50,
        },
        topTargetSegment: 'family',
        improvementSuggestions: [
          { type: 'amenity', priority: 'high', message: 'Add Gym amenity to boost score', impact: 12 },
          { type: 'imagery', priority: 'medium', message: 'Add virtual tour 3D walkthrough', impact: 18 }
        ],
        lastAiAnalysisAt: new Date(),
        analysisVersion: '1.0.0',
      });
    }

    console.log('✅ Auto-seed completed successfully!');
  } catch (error) {
    console.error('⚠️ Auto-seed error:', error.message);
  }
};

module.exports = autoSeed;
